/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.bfur64.menu;

import io.github.bfur64.menu.item.TextItem;
import org.junit.Test;

import java.util.List;

import static org.junit.Assert.*;

public class MenuTest {
    @Test
    public void testBasicMenuList() {
        MenuManager menu = new MenuManager(List.of(new TextItem("Start"), new TextItem("Fuck")));
        menu.update(KeyHit.UNKNOWN);

        assertEquals(4, menu.getDrawList().size());

        assertEquals("Start", menu.getDrawList().getFirst().out());
        assertEquals(3, menu.getDrawList().get(0).x());
        assertEquals(0, menu.getDrawList().get(0).y());

        assertEquals("Fuck", menu.getDrawList().get(1).out());
        assertEquals(3, menu.getDrawList().get(1).x());
        assertEquals(1, menu.getDrawList().get(1).y());
    }
}
