/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 */

group = "io.github.bfur64"
version = project.properties["version"] as String

var tetrueTerminal = project.properties["tetrueTerminal"] as String

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`

    id("com.github.gmazzo.buildconfig") version "6.0.10"
    id("com.vanniktech.maven.publish") version "0.36.0"
}

buildConfig {
    className("Versions")
    packageName(group.toString())
    useJavaOutput()
    buildConfigField("String", "MENU_MANAGER", "\"${project.version}\"")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenLocal()
    mavenCentral()
}

dependencies {
    // Use JUnit test framework.
    testImplementation(libs.junit)

    implementation("org.jspecify:jspecify:1.0.0")

    // Rendering Pipeline
    api("io.github.bfur64:tetrue-terminal:$tetrueTerminal")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

mavenPublishing {
    publishToMavenCentral()
    signAllPublications()

    coordinates(group.toString(), "menu-manager", version.toString())

    pom {
        name.set("menu-manager")
        description.set("A composable main menu system, built in Java using the Lanterna UI Library")
        inceptionYear.set("2026")
        url.set("https://github.com/BFUR64/menu-manager/")
        licenses {
            license {
                name.set("MIT License")
                url.set("https://opensource.org/license/mit")
                distribution.set("repo")
            }
        }
        developers {
            developer {
                id.set("BFUR64")
                name.set("Terrance")
                url.set("https://github.com/BFUR64/")
            }
        }
        scm {
            url.set("https://github.com/BFUR64/menu-manager/")
            connection.set("scm:git:https://github.com/BFUR64/menu-manager.git")
            developerConnection.set("scm:git:ssh://git@github.com/BFUR64/menu-manager.git")
        }
    }
}