/*
 * This source file was generated by the Gradle 'init' task
 */
package com.teic.menu;

import org.junit.Test;
import static org.junit.Assert.*;

public class MenuTest {
    @Test
    public void someLibraryMethodReturnsTrue() {
        assertTrue(true);
    }
}
